{{/*
Copyright 2018 AT&T Intellectual Property.  All other rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/}}

{{- if .Values.manifests.pod_test }}
{{- $envAll := . }}
---
apiVersion: v1
kind: Pod
metadata:
  name: {{ print .Release.Name "-test" }}
  annotations:
    "helm.sh/hook": test-success
    {{ tuple $envAll | include "helm-toolkit.snippets.release_uuid" }}
  labels:
{{ tuple $envAll "coredns" "test" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 4 }}
spec:
  restartPolicy: Never
  nodeSelector:
    {{ .Values.labels.coredns.node_selector_key }}: {{ .Values.labels.coredns.node_selector_value }}
  containers:
    - name: {{ .Release.Name }}-test
      image: {{ .Values.images.tags.test }}
      imagePullPolicy: {{ .Values.images.pull_policy }}
{{ tuple . .Values.pod.resources.pod_test | include "helm-toolkit.snippets.kubernetes_resources" | indent 6 }}
      command:
        - /bin/sh
        - -c
        - |
          SUCCESS=1
          while read host; do
            if [ -n "$host" ]; then
              if host "$host"; then
                echo "Successfully resolved: \"$host\""
              else
                echo "Failed to resolve: \"$host\""
                SUCCESS=0
              fi
            fi
          done < /tmp/etc/names_to_resolve
          if [ "$SUCCESS" != "1" ]; then
            echo "Test failed to resolve all names."
            exit 1
          fi
      volumeMounts:
        - name: dns-names
          mountPath: /tmp/etc
  volumes:
    - name: dns-names
      configMap:
        name: {{ $envAll.Values.service.name }}-list
        defaultMode: 0555
{{- end }}
