---
apiVersion: promenade/v1
kind: Cluster
metadata:
  name: example
  target: none
spec:
  nodes:
    n0:
      ip: 192.168.77.10
      roles:
        - master
        - genesis
      additional_labels:
        - beta.kubernetes.io/arch=amd64
    n1:
      ip: 192.168.77.11
      roles:
        - master
      additional_labels:
        - beta.kubernetes.io/arch=amd64
    n2:
      ip: 192.168.77.12
      roles:
        - master
      additional_labels:
        - beta.kubernetes.io/arch=amd64
    n3:
      ip: 192.168.77.13
      roles:
        - worker
      additional_labels:
        - beta.kubernetes.io/arch=amd64
---
apiVersion: promenade/v1
kind: Network
metadata:
  cluster: example
  name: example
  target: all
spec:
  cluster_domain: cluster.local
  cluster_dns: 10.96.0.10
  kube_service_ip: 10.96.0.1
  pod_ip_cidr: 10.97.0.0/16
  service_ip_cidr: 10.96.0.0/16
  etcd_service_ip: 10.96.232.136
  dns_servers:
    - 8.8.8.8
    - 8.8.4.4
  #http_proxy: http://proxy.example.com:8080
  #https_proxy: https://proxy.example.com:8080
---
apiVersion: promenade/v1
kind: Versions
metadata:
  cluster: example
  name: example
  target: all
spec:
  images:
    armada: quay.io/attcomdev/armada:latest
    calico:
      cni: quay.io/calico/cni:v1.9.1
      etcd: quay.io/coreos/etcd:v3.0.17
      node: quay.io/calico/node:v1.3.0
      policy-controller: quay.io/calico/kube-policy-controller:v0.6.0
    kubernetes:
      apiserver: gcr.io/google_containers/hyperkube-amd64:v1.6.4
      controller-manager: quay.io/attcomdev/kube-controller-manager:v1.6.4
      dns:
        dnsmasq: gcr.io/google_containers/k8s-dns-dnsmasq-nanny-amd64:1.14.2
        kubedns: gcr.io/google_containers/k8s-dns-kube-dns-amd64:1.14.2
        sidecar: gcr.io/google_containers/k8s-dns-sidecar-amd64:1.14.2
      etcd: quay.io/coreos/etcd:v3.0.17
      kubectl: gcr.io/google_containers/hyperkube-amd64:v1.6.4
      proxy: gcr.io/google_containers/hyperkube-amd64:v1.6.4
      scheduler: gcr.io/google_containers/hyperkube-amd64:v1.6.4
    promenade: quay.io/attcomdev/promenade:latest
    tiller: gcr.io/kubernetes-helm/tiller:v2.4.2
  packages:
    docker: docker.io=1.12.6-0ubuntu1~16.04.1
