{%- if 'kubeadm=enabled' not in config.get_first('Genesis:labels.dynamic', 'KubernetesNode:labels.dynamic') -%}
---
apiVersion: v1
kind: Pod
metadata:
  name: kubernetes-etcd
  namespace: kube-system
  labels:
    application: kubernetes
    component: etcd
    # NOTE: This label needs coordination with the etcd deployed via chart.
    kubernetes-etcd-service: enabled
spec:
  hostNetwork: true
{%- with etcd_name = config['Genesis:hostname'], client_port = 2379, peer_port = 2380, volume_name = 'kubernetes' %}
  containers:
{% include "genesis-etcd/server-container.yaml" with context %}
  volumes:
{% include "genesis-etcd/common-volumes.yaml" with context %}
{%- endwith %}
...
{%- endif %}
