---
apiVersion: v1
clusters:
- cluster:
    server: https://kubernetes:6443
    certificate-authority: /etc/kubernetes/kubelet/pki/cluster-ca.pem
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: kubelet
  name: kubelet@kubernetes
current-context: kubelet@kubernetes
kind: Config
preferences: {}
users:
- name: kubelet
  user:
    client-certificate: /etc/kubernetes/kubelet/pki/kubelet.pem
    client-key: /etc/kubernetes/kubelet/pki/kubelet-key.pem
