---
apiVersion: v1
kind: Pod
metadata:
  name: asset-loader
  namespace: kube-system
  labels:
    app: promenade
    component: asset-loader
spec:
  dnsPolicy: Default # Don't use cluster DNS.
  hostNetwork: true
  containers:
    - name: loader
      image: gcr.io/google_containers/hyperkube-amd64:v1.6.4
      command:
        - /bin/bash
        - -c
        - |-
            set -x
            while true; do
              sleep 10
              /kubectl \
                --kubeconfig /etc/kubernetes/asset-loader/kubeconfig.yaml \
                apply -f /etc/kubernetes/asset-loader/assets
            done
      volumeMounts:
        - name: config
          mountPath: /etc/kubernetes/asset-loader
          readOnly: true
  volumes:
    - name: config
      hostPath:
        path: /etc/kubernetes/asset-loader
